name: Deploy
on:
  push:
    branches: [main, official_docs_site]

jobs:
  docs:
    name: Generate Website
    runs-on: ubuntu-latest
    env:
      SPHINX_GITHUB_CHANGELOG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          git clone https://github.com/trigaten/Prompt_Systematic_Review.git
      
      - name: Build
        run: sphinx-build -b dirhtml -v docs/ build

      - name: Upload to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/

    permissions: 
      contents: write